#!/usr/bin/env bash
#source alias.sh first

rmsg() { echo -e "\e[1;31m$*\e[0m"; } #输出红色
gmsg() { echo -e "\e[1;32m$*\e[0m"; } #输出绿色
bmsg() { echo -e "\033[34;49m$*\033[0m"; } #输出蓝色


exec 1>>/var/www/html/resource/hyy_code/log/pull.log 2>&1
echo -e "-----------`date +"%F %T"`--------------"
#open alias for script
shopt -s  expand_aliases 
source /etc/profile.d/alias.sh
#cd proj path
yfp
#reset and checkout
gr && gc dev

#pull lastest code
if gs | grep "On.*branch.*dev";then
  if gs | grep "working.*directory.*clean";then
    gp
  else
    gr && gp
  fi
fi

